# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

# Provider for microsoft
module "microsoft" {
  count = 1
  enable_microsoft = true
  source  = "git::https://git@github.com/pjferrell/terraform-azurerm-k8s.git?ref=master"
  az_client_id = var.az_client_id
  az_client_secret = var.az_client_secret
  az_tenant_id = var.az_tenant_id
  az_subscription_id = var.az_subscription_id
}

# Kubeconfig files in main module directory
# (will be created in submodule directories, too)

resource "local_file" "kubeconfig-microsoft" {
  count = var.enable_microsoft ? 1 : 0
  content  = module.microsoft ? module.microsoft.kubeconfig_path_microsoft : ""
  filename = "${path.module}/kubeconfig_microsoft"

  depends_on = [module.microsoft]
}
